---

- name: default settings
  hosts: default
  roles:
    - common

- name: setup NFS server
  hosts: nfsserver
  roles:
    - nfs_server

- name: setup LDAP server
  hosts: ldapserver
  vars_files:
    - vars/ldap.yml
  roles:
    - ldap_server

- name: setup reverse proxy for jupyterlab
  hosts: reverseproxy
  roles:
    - reverse_proxy

- name: all machines
  hosts: default
  vars_files:
    - vars/ldap.yml
  roles:
    - nfs_client
    - ldap_client
    - mpi
    - jupyterlab

