---

# Coose appropriate tasks.
#
# Note that some tasks depend on varibales defined in inventory files.
# See sample-hosts.yml and modify your inventory file in accordance wtih
# your purpose and environment.

- import_playbook: apt/task.yml
- import_playbook: hostname/task.yml
- import_playbook: hosts/task.yml
#- import_playbook: user/task.yml

