---

# Choose appropriate tasks.
#
# tasks/*/README.md describes what the task does.
#
# Note that some tasks depend on varibales or host groups defined in inventory files.
# See sample-inventory.ini and modify your inventory file in accordance with
# your purpose and environment.

- name: Basic Tasks
  hosts: default
  become: yes
  tasks:
  - import_tasks: tasks/apt/task.yml
  - import_tasks: tasks/hostname/task.yml
  - import_tasks: tasks/hosts/task.yml
  - import_tasks: tasks/multihosts/task.yml

- name: NFS server
  hosts: nfsserver
  gather_facts: no
  become: yes
  vars:
    nfs_dir: /home
  tasks:
  - import_tasks: tasks/nfs-server/task.yml

- name: NFS clients
  hosts: nfsclients
  gather_facts: no
  become: yes
  vars:
    nfs_dir: /home
  tasks:
  - import_tasks: tasks/nfs-client/task.yml

- name: LDAP server
  hosts: ldapserver
  gather_facts: no
  become: yes
  vars_files:
    - ldap_vars.yaml
  tasks:
  - import_tasks: tasks/ldap-server/task.yml

- name: LDAP clients
  hosts: default
  gather_facts: no
  become: yes
  vars_files:
    - ldap_vars.yaml
  tasks:
  - import_tasks: tasks/ldap-client/task.yml

- name: LDAP users
  hosts: ldapserver
  gather_facts: no
  become: yes
  vars_files:
    - ldap_vars.yaml
  tasks:
  - import_tasks: tasks/ldap-users/task.yml

- name: CUDA
  hosts: gpus
  gather_facts: no
  become: yes
  tasks:
  - import_tasks: tasks/nvidia-cuda-toolkit/task.yml
  - import_tasks: tasks/nvidia-cudnn/task.yml

- name: pytorch GPU
  hosts: gpus
  gather_facts: no
  become: yes
  tasks:
  - import_tasks: tasks/pytorch/task_gpu.yml
    
- name: pytorch CPU
  hosts: cpus
  gather_facts: no
  become: yes
  tasks:
  - import_tasks: tasks/pytorch/task_cpu.yml
    
- name: tensorflow
  hosts: default
  gather_facts: no
  become: yes
  tasks:
#  - import_tasks: tasks/tensorflow/task.yml

- name: Other tasks
  hosts: default
  gather_facts: no
  become: yes
  tasks:
  - import_tasks: tasks/jupyterhub/task.yml
#  - import_tasks: tasks/apache/task.yml
#  - import_tasks: tasks/docker/task.yml
#  - import_tasks: tasks/jupyterlab/task.yml

# - name: reboot server
#   hosts: nfsserver
#   gather_facts: no
#   become: yes
#   tasks:
#     reboot

- name: reboot clients
  hosts: nfsclients
  gather_facts: no
  become: yes
  tasks:
  - reboot:
    
