---
- name: Sample Playbook
  hosts: default
  become: yes


# Choose appropriate tasks.
#
# tasks/*/README.md describes what the task does.
#
# Note that some tasks depend on varibales defined in inventory files.
# See sample-inventory.ini and modify your inventory file in accordance wtih
# your purpose and environment.

  tasks:
  - import_tasks: tasks/apt/task.yml
  - import_tasks: tasks/hostname/task.yml
  - import_tasks: tasks/hosts/task.yml
  - import_tasks: tasks/users/task.yml

# Example tasks
#  - import_tasks: tasks/jupyterlab/task.yml
