---
- name: Sample Playbook
  hosts: default
  become: yes


# Coose appropriate tasks.
#
# Note that some tasks depend on varibales defined in inventory files.
# See sample-hosts.yml and modify your inventory file in accordance wtih
# your purpose and environment.

  tasks:
  - import_tasks: tasks/apt/task.yml
  - import_tasks: tasks/hostname/task.yml
  - import_tasks: tasks/hosts/task.yml
  - import_tasks: tasks/users/task.yml

