- name: install pip3
  apt:
    name: python3-pip
    state: present

- name: install pytorch
  pip:
    executable: pip3
    name:
    - numpy
    - torch==1.9.1
    - torchvision==0.10.1
    - torchaudio==0.9.1

- name: install torch-{scatter,sparse,cluster,geometric}
  pip:
    executable: pip3
    extra_args: -f https://pytorch-geometric.com/whl/torch-1.9.0+cpu.html
    name:
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-geometric

