- name: install nfs client
  apt:
    name: nfs-common
    state: present

- name: mount the NFS volume on the manager host
  mount:
    src: "{{ hostvars[groups['nfsserver'][0]].ethipv4 }}:{{ nfs_dir }}"
    path: "{{ nfs_dir }}"
    opts: rw,noatime
    boot: yes
    state: mounted
    fstype: nfs
    
