- name: create venv for jupyterlab
  pip:
    name:
      - setuptools
      - pip
    state: latest
    virtualenv: "/home/mdxuser/.python-venv"
    virtualenv_command: '/usr/bin/python3 -m venv'

- name: install jupyterlab
  pip:
    name:
      - jupyterlab
    virtualenv: "/home/mdxuser/.python-venv"

- name: daemonize jupyterlab through systemd
  template:
    src: templates/jupyterlab.service.j2
    dest: /etc/systemd/system/jupyterlab.service
  vars:
    jupyterlab_user: mdxuser
    jupyterlab_group: mdxuser
    jupyterlab_directory: /home/mdxuser


- name: make sure enable and run jupyterlab daemon
  systemd:
    name: jupyterlab
    state: started
    enabled: yes
    daemon_reload: yes
