- name: copy the deb packages and configuration files
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
    - ./files/lustre-client-modules-5.4.0-77-generic_2.12.6-ddn13-1_amd64.deb
    - ./files/lustre-client-utils_2.12.6-ddn13-1_amd64.deb
    - ./files/lustre_config_ubuntu_rdma.tgz

- name: install deb packages
  apt:
    deb: "{{ item }}"
  with_items:
    - /tmp/lustre-client-modules-5.4.0-77-generic_2.12.6-ddn13-1_amd64.deb
    - /tmp/lustre-client-utils_2.12.6-ddn13-1_amd64.deb

- name: set up fstab
  blockinfile:
    path: /etc/fstab
    block: |
      172.17.8.40@o2ib10:172.17.8.41@o2ib10:/fast     /fast           lustre  network=o2ib10,flock,noauto,defaults 0 0
      172.17.8.56@o2ib10:172.17.8.57@o2ib10:/large    /large          lustre  network=o2ib10,flock,noauto,defaults 0 0

- name: mkdir for lustre configs
  file: path=/etc/sysconfig state=directory owner=root group=root mode=0755

- name: copy lustre configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: ./files/lustre_config/etc/lnet.conf.ddn, dest: /etc/lnet.conf.ddn }
    - { src: ./files/lustre_config/etc/sysconfig/lustre_client, dest: /etc/sysconfig/lustre_client }
    - { src: ./files/lustre_config/etc/modprobe.d/lustre.conf, dest: /etc/modprobe.d/lustre.conf }
    - { src: ./files/lustre_config/etc/init.d/lustre_client, dest: /etc/init.d/lustre_client }
    - { src: ./files/lustre_config/usr/lib/systemd/system/lustre_client.service, dest: /usr/lib/systemd/system/lustre_client.service }
    - { src: ./files/lustre_config/var/lib/cloud/scripts/per-boot/lustre-config.sh, dest: /var/lib/cloud/scripts/per-boot/lustre-config.sh }

- name: file permissions
  file:
    path: "{{ item }}"
    mode: '0755'
  with_items:
    - /etc/init.d/lustre_client
    - /var/lib/cloud/scripts/per-boot/lustre-config.sh

- name: enable lustre_client daemon
  service:
    name: lustre_client
    enabled: yes
    state: started

