- name: ensure nfs directory exists
  file:
    path: "{{ nfs_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: install nfs server
  apt:
    name: nfs-kernel-server
    state: present

- name: export nfs dir via NFS
  lineinfile:
    path: /etc/exports
    state: present
    regexp: "^{{ nfs_dir }} "
    line: "{{ nfs_dir }} {{ ethipv4prefix }}(rw)"

- name: re-export all directories
  command: exportfs -ra

    
