---

# ansible-playbook openldap-cluster.yml -i openldap-cluster.ini

- name: common stuff
  hosts: all
  become: yes
  tasks:
  - name: apt update cache
    apt:
      update_cache: yes
  - name: apt upgrade
    apt:
      upgrade: yes
  - name: install common packages
    apt:
      state: present
      name:
      - emacs
      - gcc
      - make
      - cmake
      - tmux
      - subversion
  - name: setup hostname
    hostname:
      name: "{{ hostname }}"
  - name: deploy /etc/hosts
    template:
      src: templates/etc_hosts.j2
      dest: /etc/hosts
    vars:
      etc_host_group: default

- name: LDAP server
  hosts: manager
  become: yes
  gather_facts: False
  tasks:
  - import_tasks: ..//ldap-server/task.yml

- name: LDAP clients
  hosts: all
  become: yes
  gather_facts: False
  tasks:
  - import_tasks: ..//ldap-client/task.yml

- name: NFS server
  hosts: manager
  become: yes
  gather_facts: False
  tasks:
  - import_tasks: ../ldap-users/task.yml
  - import_tasks: ../nfs-server/task.yml
    
- name: NFS clients
  hosts: workers
  become: yes
  gather_facts: False
  tasks:
  - import_tasks: ..//nfs-client/task.yml
    
