#
# install client packages
#
- name: install LDAP client packages
  apt:
    state: present
    name:
    - sssd
    - libnss-ldap
    - libpam-ldap
    - ldap-utils

#
# make a line like 
#  base dc=myldap,dc=mdx,dc=jp
# in /etc/ldap.conf
#
- name: change base /etc/ldap.conf
  lineinfile:
    path: /etc/ldap.conf
    regexp: "^base (.*)$"
    line:    "base {{ ldap_domain }}"

#
# make a line like 
#  uri ldap://ikura000/
# in /etc/ldap.conf
#
- name: change uri /etc/ldap.conf
  lineinfile:
    path: /etc/ldap.conf
    regexp: "^uri (.*)$"
    line:    "uri ldap://{{ hostvars[groups['ldapserver'][0]].ethipv4 }}/"
    backup: yes
    
#
# make a line like 
#  rootbinddn cn=admin,dc=myldap,dc=mdx,dc=jp
# in /etc/ldap.conf
#
- name: change rootbinddn /etc/ldap.conf
  lineinfile:
    path: /etc/ldap.conf
    regexp: "^rootbinddn (.*)$"
    line:    "rootbinddn cn=admin,{{ ldap_domain }}"
    
#
# put LDAP administrator (ldap_root_password) password
# in /etc/ldap.secret
# TODO: I am still not sure whether we should put
# LDAP administrator password or
# domain admin password (domain_password).
# it seems more logical to use domain admin password
# here
#
# TODO:
# AFAIK, /etc/ldap.secret must have a plain password
# 
- name: generate /etc/ldap.secret
  copy:
    dest: /etc/ldap.secret
#    content: "{{ ldap_root_password }}"
    content: "{{ ldap_domain_password }}"
    mode: "0600"
    owner: root
    backup: yes

#
# this is a trick to make "su USER_NAME" succeed
#
- name: change /etc/pam.d/common-password
  lineinfile:
    path: /etc/pam.d/common-password
    backrefs: yes
    regexp: "^password(.*) use_authtok(.*)$"
    line:    'password\1 \2$'
    backup: yes

- name: put sssd.conf
  template:
    src: templates/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: "0600" 
  vars:
    ldapserver_addr: "{{ hostvars[groups['ldapserver'][0]].hostname }}"
    
#
# you need to do this after you set things up.
# otherwise it keeps saying "no such user", 
# presumably due to a negative chache
#
# TODO: should this be sssd? (not sure as
# nscd is suggested when we install libnss-ldap
# etc.)
#
- name: restart sssd
  service:
    name: sssd
    state: restarted
    
