- name: create /etc/netplan/mdx.yml
  blockinfile:
    path: /etc/netplan/mdx.yml
    create: yes
    marker: ""
    block: |
      network:
        ethernets:
          ens160:
            dhcp4: true
            match:
              name: ens160
          ens192:
            dhcp4: true
            match:
              name: ens192
        version: 2

- name: netplan apply
  shell: netplan apply

