- name: create /etc/netplan/mdx.yaml
  blockinfile:
    path: /etc/netplan/mdx.yaml
    create: yes
    marker: ""
    block: |
      network:
        ethernets:
          default:
            dhcp4: true
            match:
              name: ens*
            dhcp-identifier: mac
            optional: true
        version: 2

- name: netplan apply
  shell: netplan apply

