

- name: include user definitions
  include_vars:
    file: vars/userlist.yml


- name: make sure users exist or not
  user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
  loop: "{{ users }}"


- name: put authorized key
  authorized_key:
    state: present
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  loop: "{{ users }}" 
  when: item.state == "present"
     
