- name: copy the OFED driver image
  copy:
    src: ./files/MLNX_OFED_LINUX-5.1-2.6.2.0-ubuntu20.04-x86_64.iso
    dest: /tmp

- name: mount the OFED iso image
  mount:
    path: /mnt/mlnx_ofed
    src: /tmp/MLNX_OFED_LINUX-5.1-2.6.2.0-ubuntu20.04-x86_64.iso
    fstype: iso9660
    opts: ro,loop
    state: mounted
    fstab: /tmp/tmp.fstab

- name: run the MLNX_OFED installation script
  shell: /mnt/mlnx_ofed/mlnxofedinstall --guest --force --add-kernel-support

- name: restart openibd daemon
  service:
    name: openibd
    enabled: yes
    state: started

- name: unmount the OFED iso image
  mount:
    path: /mnt/mlnx_ofed
    src: /tmp/MLNX_OFED_LINUX-5.1-2.6.2.0-ubuntu20.04-x86_64.iso
    fstype: iso9660
    opts: ro,loop
    state: unmounted
    fstab: /tmp/tmp.fstab

- name: delete /mnt/mlnx_ofed
  file:
    path: /mnt/mlnx_ofed
    state: absent

