#
# install slapd
#
- name: install slapd on master
  apt:
    state: present
    name:
    - slapd
    - ldap-utils

# if ldap_root_password_hash is not defined, generate it from root password
- name: obtain hash of root password
  command: slappasswd -s {{ ldap_root_password }}
  register: slappasswd_root
  when: ldap_root_password_hash is not defined

- name: set ldap_root_password_hash
  set_fact:
    ldap_root_password_hash: "{{ slappasswd_root.stdout }}"
  when: ldap_root_password_hash is not defined

# set root password
- name: generates /tmp/change_root_pw.ldif
  template:
    src: templates/change_root_pw.ldif.j2
    dest: /tmp/change_root_pw.ldif

#
# generate ldif to change the administrator password
# (defined in the inventory file)
#
- name: master generates /tmp/change_root_pw.ldif
  template:
    src: templates/change_root_pw.ldif.j2
    dest: /tmp/change_root_pw.ldif

#
# actually change the administrator password
#
- name: master changes LDAP root pw
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/change_root_pw.ldif

# if ldap_domain_password_hash is not defined, generate it from domain password
- name: obtain hash of domain password
  command: slappasswd -s {{ ldap_domain_password }}
  register: slappasswd_domain
  when: ldap_domain_password_hash is not defined

- name: set ldap_domain_password_hash
  set_fact:
    ldap_domain_password_hash: "{{ slappasswd_domain.stdout }}"
  when: ldap_domain_password_hash is not defined

#
# generate ldif file to make the LDAP domain of this cluster
# (defined in the inventory file)
#
- name: master generates /tmp/make_domain.ldif
  template:
    src: templates/make_domain.ldif.j2
    dest: /tmp/make_domain.ldif

#
# actually make the LDAP domain
#
- name: master makes an LDAP domain
  shell: ldapsearch -Y EXTERNAL -H ldapi:/// -s base -b {{ ldap_domain }} || slapadd -l /tmp/make_domain.ldif
