---

# Role: common
# Configure hostname and /etc/hosts

- name: setup hostname
  hostname:
    name: "{{ hostname }}"

- name: deploy /etc/hosts
  template:
    src: templates/etc_hosts.j2
    dest: /etc/hosts
  vars:
    etc_host_group: default

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
