---
- name: apt
  hosts: default
  become: yes


  tasks:
  - name: install essential packages
    apt:
      state: present
      name:
      - emacs
      - gcc
      - make
      - cmake
      - tmux

# change list of `name` to install packages you need
