- name: create ansible user
  user:
    name: ansible
    groups: adm,sudo
    home: /var/ansible
    create_home: yes

- name: make ansible user be sudoable with nopass
  blockinfile:
    path: /etc/sudoers.d/ansible
    create: yes
    block: |
      ansible ALL=(ALL) NOPASSWD:ALL

- name: make sure /var/ansible/.ssh exists
  file:
    path: /var/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible

# Following tasks are invoked on the 1st shot 
# (HOME of mdxuser is not moved yet)
#
- name: check /home/mdxuser exists
  stat: path=/home/mdxuser
  register: home_mdxuser_stat
           
- name: copy mdxuser authkey to ansible user if /home/mdxuser exists
  copy:
    src: /home/mdxuser/.ssh/authorized_keys
    dest: /var/ansible/.ssh/authorized_keys
    remote_src: yes
    owner: ansible
    group: ansible
    mode: "0600"
  when: home_mdxuser_stat.stat.exists

#
- name: check /home.local/mdxuser exists
  stat: path=/home.local/mdxuser
  register: home_local_mdxuser_stat

- name: copy mdxuser authkey to ansible user if /home.local/mdxuser exists
  copy:
    src: /home.local/mdxuser/.ssh/authorized_keys
    dest: /var/ansible/.ssh/authorized_keys
    remote_src: yes
    owner: ansible
    group: ansible
    mode: "0600"
  when: home_local_mdxuser_stat.stat.exists

################################
# mv and change $HOME of mdxuser
# This play is invoked on only the 1st shot where /home/mdxuser exists
#
- name: make sure /home.local exists
  vars:
    ansible_user: ansible
  file:
    path: /home.local
    state: directory

- name: check /home/mdxuser exists
  vars:
    ansible_user: ansible
  stat: 
    path: /home/mdxuser
  register: home_mdxuser_stat

- name: copy home dir of mdxuser
  vars:
    ansible_user: ansible
  command: cp -a /home/mdxuser /home.local/
  when: home_mdxuser_stat.stat.exists

# XXX: should be gentle...
- name: killall mdxuser processes before change homedir
  vars:
    ansible_user: ansible
  shell:
    cmd: killall -KILL -u mdxuser || true
  when: home_mdxuser_stat.stat.exists

- name: make sure mdxuser's homedir is /home.local/mdxuser
  vars:
    ansible_user: ansible
  user:
    name: mdxuser
    home: /home.local/mdxuser
  when: home_mdxuser_stat.stat.exists

- name: remove the original home dir of mdxuser
  vars:
    ansible_user: ansible
  file:
    path: /home/mdxuser
    state: absent
  when: home_mdxuser_stat.stat.exists

################################
# cleanup user ansible because moving /home/mdxuser is done
#

# XXX: should be gentle...
- name: killall processes of user ansible before remove it
  shell:
    cmd: killall -KILL -u ansible || true

- name: make sure user ansible does not exist
  user:
    name: ansible
    state: absent

- name: make sure /var/ansible does not exist
  file:
    path: /var/ansible
    state: absent

