
- name: apt update cache
  apt:
    update_cache: yes

# - name: apt upgrade
#   apt:
#     upgrade: yes

# change list of `name` to install packages you need
- name: install basic packages
  apt:
    state: present
    name:
    - python3-pip
    - emacs
    - gcc
    - make
    - cmake
    - tmux

