- name: copy cudnn packages to the virtual machine
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
  - ../files/libcudnn8_8.2.2.26-1+cuda11.4_amd64.deb
  - ../files/libcudnn8-dev_8.2.2.26-1+cuda11.4_amd64.deb

- name: apt update
  apt:
    update_cache: yes

- name: install cudnn libraries
  apt:
    deb: "{{ item }}"
  with_items:
      - /tmp/libcudnn8_8.2.2.26-1+cuda11.4_amd64.deb
      - /tmp/libcudnn8-dev_8.2.2.26-1+cuda11.4_amd64.deb
