---

# ansible-playbook openldap-cluster.yml -i openldap-cluster.ini

- name: common stuff
  hosts: all
  become: yes
  tasks:
  - name: apt update cache
    apt:
      update_cache: yes
  - name: apt upgrade
    apt:
      upgrade: yes
  - name: install common packages
    apt:
      state: present
      name:
      - emacs
      - gcc
      - make
      - cmake
      - tmux
      - subversion
  - name: setup hostname
    hostname:
      name: "{{ hostname }}"
  - name: deploy /etc/hosts
    template:
      src: templates/etc_hosts.j2
      dest: /etc/hosts
    vars:
      etc_host_group: default

- name: manager-only things
  hosts: manager
  become: yes
  gather_facts: False
  tasks:
  - import_tasks: tasks/ldap-server/task.yml
  - import_tasks: tasks/ldap-users/task.yml
  - import_tasks: tasks/nfs-server/task.yml

- name: common things after manager is done
  hosts: all
  become: yes
  gather_facts: False
  tasks:
  - import_tasks: tasks/ldap-client/task.yml

- name: worker-only things after manager is done
  hosts: workers
  become: yes
  gather_facts: False
  tasks:
  - import_tasks: tasks/nfs-client/task.yml
    
